import type { Metadata } from "next";

import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

import "./globals.css";
import ToasterProvider from "@/providers/ToasterProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col justify-between bg-blue-200 text-gray-800 max-w-6xl mx-auto">
        <ToasterProvider />
        <Header />
        <main className="mx-auto max-w-4xl  p-6 bg-white shadow-md rounded-lg my-60">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
