import type { Metadata } from "next";

import ToasterProvider from "@/providers/ToasterProvider";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col justify-between bg-blue-200 text-gray-800 max-w-6xl mx-auto">
        <ToasterProvider />
        <Header />
        <main className="flex-grow mt-32">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
